export default function Head() {
  return (
    <>
      <title>João Jesus | Frontend Developer</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />

      <link rel='preconnect' href='https://fonts.googleapis.com' />
      <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin='' />

      {/* <link rel='icon' href='/favicon.ico' /> */}

      <link
        href='https://fonts.googleapis.com/css2?family=DM+Sans&family=Poppins:wght@400;500;600&display=swap'
        rel='stylesheet'
        precedence='default'
      />
    </>
  )
}
